// Generated by CoffeeScript 1.8.0
(function() {
  window.app = window.app || {};

  $(function() {
    $('#releaseDate').datepicker();
    return new app.LibraryView();
  });

}).call(this);

//# sourceMappingURL=app.js.map
