// Generated by CoffeeScript 1.8.0
(function() {
  window.app = window.app || {};

  window.app.BookView = Backbone.View.extend({
    tagName: 'div',
    className: 'bookContainer',
    template: _.template($('#bookTemplate').html()),
    render: function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    },
    events: {
      'click .delete': 'deleteBook'
    },
    deleteBook: function() {
      this.model.destroy();
      return this.remove();
    }
  });

}).call(this);

//# sourceMappingURL=book.js.map
