// Generated by CoffeeScript 1.8.0
(function() {
  window.app = window.app || {};

  window.app.LibraryView = Backbone.View.extend({
    el: '#books',
    initialize: function(initialBooks) {
      this.collection = new app.Library(initialBooks);
      this.collection.fetch({
        reset: true
      });
      this.render();
      this.listenTo(this.collection, 'add', this.renderBook);
      return this.listenTo(this.collection, 'reset', this.render);
    },
    events: {
      'click #add': 'addBook'
    },
    render: function() {
      return this.collection.each(function(item) {
        return this.renderBook(item);
      }, this);
    },
    renderBook: function(item) {
      var bookView;
      bookView = new app.BookView({
        model: item
      });
      return this.$el.append(bookView.render().el);
    },
    addBook: function(e) {
      var formData;
      e.preventDefault();
      formData = {};
      $('#addBook div').children('input').each(function(i, el) {
        if ($(el).val() !== '') {
          if (el.id === 'keywords') {
            formData[el.id] = [];
            return _.each($(el).val().split(' '), function(keyword) {
              return formData[el.id].push({
                keyword: keyword
              });
            });
          } else if (el.id === 'releaseDate') {
            return formData[el.id] = $('#releaseDate').datepicker('getDate').getTime();
          } else {
            return formData[el.id] = $(el).val();
          }
        }
      });
      return this.collection.create(formData);
    }
  });

}).call(this);

//# sourceMappingURL=library.js.map
