// Generated by CoffeeScript 1.8.0
(function() {
  window.app = window.app || {};

  window.app.Book = Backbone.Model.extend({
    defaults: {
      coverImage: 'img/placeholder.png',
      title: 'No title',
      author: 'Unknown',
      releaseDate: 'Unknown',
      keywords: 'None'
    },
    parse: function(response) {
      response.id = response._id;
      return response;
    }
  });

}).call(this);

//# sourceMappingURL=book.js.map
