// Generated by CoffeeScript 1.8.0
(function() {
  window.app = window.app || {};

  window.app.Library = Backbone.Collection.extend({
    model: app.Book,
    url: '/api/books'
  });

}).call(this);

//# sourceMappingURL=library.js.map
